nelmio_api_doc:
    documentation:
        info:
            title: REST API Symfony assignment
            description: This app is made for making calculations with an old money system and for retrieving example products thanks to symfony.
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
