controllers:
    resource:
        path: ../src/Controller/Api/v1
        namespace: App\Controller\Api\v1
    type: attribute
    prefix: /api/v1
# config/routes.yaml
app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }